name: "dps"
version: "1.0.0"
config-version: 2

profile: "dps"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  dps:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table
